### PR TITLE
Redmi 9: Rewrite overlay based on official LineageOS

### PR DESCRIPTION
**Pull request by ghost**
Big improvement especially auto brightness

### CODE REVIEW

**Comment by phhusson** [comment]
If it improvies auto brightness why do you change config_mobile_tcp_buffers ...

**Comment by ghost** [comment]
I have deleted networkAttributes, radioAttributes and config_mobile_tcp_buffers.

**Comment by phhusson** [comment]
Hmmm? Why all the closes?

**Comment by ghost** [comment]
> Hmmm? Why all the closes?

I'm making sure everything is correct.
Started without any debugging stuff on rw-system.sh.
Then try anything useful from Treble App.
Once everything is correct I will reopen them.

Now I reopen them again.

**Comment by phhusson** [comment]
Understood. The "standard" way to mark a PR "work in progress" is to prepend the name of the PR with "WIP:" like renaming yours to `WIP: Redmi 9: Rewrite overlay based on official LineageOS `

**Comment by ghost** [comment]
Ready to merge @phhusson

**Pull request merged**
