### PR TITLE
Update power_profile.xml

### PR DESCRIPTION
**Pull request by flexynos**
Fixes for Andrey 🙂

### CODE REVIEW

**Comment by phhusson** [comment]
https://www.gsmarena.com/samsung_galaxy_a10s-9793.php This says 4000 though

**Comment by flexynos** [comment]
Maybe make upgrade battery for guy?

**Comment by phhusson** [comment]
I'm not going to merge the battery upgrade one person did on their unit, breaking overlay for all other people...?

**Comment by flexynos** [comment]
Yes, it seems to me that no one except him uses this device, okay, enough jokes, I’ll close it now. Good evening!

**Pull request closed without merging**
