### PR TITLE
Add overlays for Galaxy A10s

### PR DESCRIPTION
**Pull request by nnhra**
I created this and tested on my Galaxy A10s. It works perfectly and I didn't get any problem while using the overlay

### CODE REVIEW

**Comment by phhusson** [comment]
Merged

**Comment by ponces** [comment]
> Merged

Why the revert of b9b22a8963127a8b47032f2f7b62bcaf744e8da0?
What does it have to do with an a10s overlay?

**Comment by phhusson** [comment]
@ponces  I didn't merge those last two commits, they clearly were meant for another ROM (I'm guessing that git is now used to make an A10s-specific GSI)

**Comment by ponces** [comment]
> @ponces I didn't merge those last two commits, they clearly were meant for another ROM (I'm guessing that git is now used to make an A10s-specific GSI)

I guess you did unintentionally then :)
https://github.com/TrebleDroid/vendor_hardware_overlay/commit/fd94a9a2a250464b29cfdde5cafec0d389512771

**Comment by phhusson** [comment]
thx

**Pull request closed without merging**
