### PR TITLE
Redmi 9: update overlays

### PR DESCRIPTION
**Pull request by ghost**
Changelog:
- add missing config_dozeAfterScreenOffByDefault
- readjust rounded_corner_content_padding also  status_bar_padding_start & status_bar_padding_end
- add more rounded corner and status bar items (from stock, different from generic)
- add navigation bar and quick qs items (from stock, different from generic)
- add config_fillMainBuiltInDisplayCutout
- add config_mainBuiltInDisplayCutoutRectApproximation

Done.

### CODE REVIEW

**Comment by ghost** [comment]
Please merge sir @phhusson (sorry for pinging).

I've been using this overlay for a few days without any problems.
The padding is also good (compared to the *ugly* padding on the official lineageos).

IMG_20240331_211003_091208

**Comment by ghost** [comment]
Force pushed messy commits @phhusson

**Comment by ghost** [comment]
A14 QPR2 won't boot.
Xiaomi only releases kernels for R vendors.
Looks like I need to try to patch a custom kernel so the A14 QPR2 can boot.
For now, I am closing this PR.
And may need to rewrite the overlay for the R vendor later.

**Comment by phhusson** [comment]
> A14 QPR2 won't boot.

Well that's no problem we'll fix it?
>  Looks like I need to try to patch a custom kernel so the A14 QPR2 can boot.

No? We'll fix GSI?


No need to close this PR because of this?

**Comment by ghost** [comment]
> Well that's no problem we'll fix it?

> No? We'll fix GSI?

> No need to close this PR because of this?

Reopened.

But can you hold it for a while?
I'm still looking for the right numbers for:

- rounded_corner_content_padding
- status_bar_padding_end
- status_bar_padding_start

Because the status bar items are a bit unbalanced when qs is pulled down.

Thanks

**Comment by phhusson** [comment]
No problem. Remove the WIP: in the title when you think it can be merged

**Comment by ghost** [comment]
> No problem. Remove the WIP: in the title when you think it can be merged

Done.

Sir, does gsi have `recents_task_view_rounded_corners_radius` configuration?
I want to make the application look rounded when accessing the recents screen.

Like this:
recent_screen1

Instead of like this
recent_screen2

**Comment by phhusson** [comment]
This value doesn't exist in Android:
https://cs.android.com/search?q=recents_task_view_rounded_corners_radius&sq=

**Pull request merged**
