### PR TITLE
 Add overlay files for Nubia red magic 6 series (6 6s 6 pro 6s pro)

### PR DESCRIPTION
**Pull request by boydaihungst**
They use the same fingerprint: nubia/NX669J. 
Tested on 6s pro.

### CODE REVIEW

**Comment by boydaihungst** [comment]
This will fix auto-brightness not working and FOD UI. I will add a merge request to [device_phh_treble](https://github.com/TrebleDroid/device_phh_treble) to fix FOD soon.

**Comment by phhusson** [comment]
Just to confirm, in stock ROM you literally had config_udfps_sensor_props already? It wasn't auto-detected from some /sys or prop that could be read by GSI?

**Comment by boydaihungst** [comment]
> Just to confirm, in stock ROM you literally had config_udfps_sensor_props already? It wasn't auto-detected from some /sys or prop that could be read by GSI?

Yep. The item values are taken from stock Rom (hardcode in SystemUI.apk). They are using FPUI.java (which doesn't exist in GSI SystemUI.apk) to trigger fingerprint events and create a fingerprint mask (which also doesn't exist in GSI).
image.

**Comment by phhusson** [comment]
That's uh, a weird way to do it, but ok, thanks.

**Pull request merged**
