### PR TITLE
Add overlay for Doogee V Max

### PR DESCRIPTION
**Pull request by Vgdn1942**

### CODE REVIEW

**Comment by phhusson** [comment]
Is it tested? What does it fix?

**Comment by phhusson** [comment]
power profile is obviously completely wrong

**Comment by Vgdn1942** [comment]
@phhusson Yes, it's tested. Corrects the correct value of battery capacity and general overlays from the device firmware.

**Comment by Vgdn1942** [comment]
> power profile is obviously completely wrong

Why? My device does have a 22000 mAh battery. This was taken from the stock firmware.

**Comment by phhusson** [comment]
Because your screen doesn't consume 0.1mA when brightness is at the maximum.

**Comment by Vgdn1942** [comment]
> Because your screen doesn't consume 0.1mA when brightness is at the maximum.

This was the case in the files from the stock system. I can remove this and leave only the battery capacity.

**Comment by Vgdn1942** [comment]
> Because your screen doesn't consume 0.1mA when brightness is at the maximum.

I have corrected the incorrect values, please have a look now.

**Comment by phhusson** [comment]
Corrected how?

**Comment by Vgdn1942** [comment]
> Corrected how?

Matched the values ​​from FrameworkResOverlay (current) and framework-res

**Pull request merged**
