### PR TITLE
Updated Redmi Note 10 5G / POCO M3 Pro/5G overlay

### PR DESCRIPTION
**Pull request by khaeruirgi**

### CODE REVIEW

**Comment by phhusson** [comment]
What does it change? Why? What does this fix?

**Comment by khaeruirgi** [comment]
Fixed some WiFi and mobile network issues, default refresh rate and brightness levels.

**Comment by phhusson** [comment]
Which issues?

**Comment by khaeruirgi** [comment]
Screen brightness is always set to very bright light, actually this patch has been merged in phhusion/vendor_hardware_overlay but not here, some gsi use this repo not the other one

**Pull request closed without merging**
