### PR TITLE
Add overlay for gta4l: Samsung A7 tablet model SM-T50x

### PR DESCRIPTION
**Pull request by ildar**
fixes brightness/autobrightness issues

### CODE REVIEW

**Comment by zenfyrdev** [comment]
I believe most of those values, besides arrays and `config_automatic_brightness_available`, are platform default. Does anything change without those?

https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/core/res/res/values/config.xml

**Comment by phhusson** [comment]
@melontini thanks for those remarks, which are technically correct, but I've long abandonned cleaning those up.
Since overlay is still one of the cleanest we receive here...

**Comment by zenfyrdev** [comment]
Yeah, fair enough. Btw, have you considered setting up CI to run tests automatically?

**Comment by phhusson** [comment]
Well I had it on https://github.com/phhusson/vendor_hardware_overlay, but I remember it was rather annoying and I don't really feel like going through it again

**Pull request merged**
