### PR TITLE
A32: Update from latest framework-res

### PR DESCRIPTION
**Pull request by realahnet**
I have tested these and the changes do infact  work

### CODE REVIEW

**Comment by phhusson** [comment]
What does it change?

**Comment by realahnet** [comment]
> What does it change?

included things like changing the thresholds or the ammount it darkens when going into aod and i have seen it work. before it took a bit too long and it was weird. The newly imported values also had an effect on the screen brightness, it is brighter when pushing it to max and autobrightness seems to respond quicker to light changes. Tested roughly but i did see the change. I also rebased each file on the newer firmware in hoping to fix issues with my sms not being recieved by many a32 users  that have been encountering on the newer firmware. I dont think its overlay related but i did see configs there. Sorry for not clarifying in the original post.

**Comment by boydaihungst** [comment]
@ahnet-69 
There are 2 `config_defaultPinnerServiceFiles`. That makes build error.

**Comment by phhusson** [comment]
@boydaihungst reverted, thanks.

**Pull request merged**
